### ISSUE TITLE
Socket continua aberto depois do servidor ser finalizado

### ISSUE THREAD

**Issue by wmaikon** [nistarok/testingSocket#1]
Após o server1.py ou o server2.py receber uma mensagem para descriptografar e fechar o servidor, o socket referente ao server que recebeu a mensagem não é fechado corretamente, fazendo com que o socket seja liberado posteriormente após alguns minutos.

Não é um problema sério, mas evita que seja possível iniciar o servidor novamente logo em seguida caso seja necessário.

Se não conseguir olhar isto agora, eu olho mais tarde :)
![selection_033](https://cloud.githubusercontent.com/assets/351910/15396363/22ea2192-1db2-11e6-9dbb-ba2c79682358.png)

**Comment by nistarok** [comment]
@wmaikon Opa,
Fiz uma alteração, acho que deu certo. Pode testar aí.

**Comment by nistarok** [comment]
#123 #asd

- [ ] 

- 1.
